"""Typed failures for semantic validation and deterministic lowering."""

from enum import StrEnum


class SemanticFailureCode(StrEnum):
    UNKNOWN_RELATION_SOURCE = "UNKNOWN_RELATION_SOURCE"
    UNKNOWN_DERIVED_ATTRIBUTE = "UNKNOWN_DERIVED_ATTRIBUTE"
    INVALID_CTE_REFERENCE = "INVALID_CTE_REFERENCE"
    DUPLICATE_CTE_ID = "DUPLICATE_CTE_ID"
    CTE_DEPENDENCY_CYCLE = "CTE_DEPENDENCY_CYCLE"
    INVALID_SCOPE_REFERENCE = "INVALID_SCOPE_REFERENCE"
    AMBIGUOUS_SCOPE_REFERENCE = "AMBIGUOUS_SCOPE_REFERENCE"
    NO_RELATIONSHIP_PATH = "NO_RELATIONSHIP_PATH"
    UNKNOWN_SEMANTIC_ENTITY = "UNKNOWN_SEMANTIC_ENTITY"
    UNKNOWN_SEMANTIC_ATTRIBUTE = "UNKNOWN_SEMANTIC_ATTRIBUTE"
    UNKNOWN_RELATIONSHIP = "UNKNOWN_RELATIONSHIP"
    AMBIGUOUS_RELATIONSHIP_PATH = "AMBIGUOUS_RELATIONSHIP_PATH"
    FANOUT_UNSAFE_PATH = "FANOUT_UNSAFE_PATH"
    INVALID_POPULATION_CONTRACT = "INVALID_POPULATION_CONTRACT"
    INVALID_GRAIN = "INVALID_GRAIN"
    INVALID_AGGREGATION = "INVALID_AGGREGATION"
    INVALID_CALCULATION = "INVALID_CALCULATION"
    UNSUPPORTED_FUNCTION = "UNSUPPORTED_FUNCTION"
    UNSUPPORTED_OPERATOR = "UNSUPPORTED_OPERATOR"
    MISSING_REQUIRED_FILTER = "MISSING_REQUIRED_FILTER"
    UNSUPPORTED_SEMANTIC_ADDITION = "UNSUPPORTED_SEMANTIC_ADDITION"
    PROJECTION_MISMATCH = "PROJECTION_MISMATCH"
    ORDER_LIMIT_MISMATCH = "ORDER_LIMIT_MISMATCH"
    UNSUPPORTED_CORRELATED_REFERENCE = "UNSUPPORTED_CORRELATED_REFERENCE"
    UNSUPPORTED_SET_OPERATION = "UNSUPPORTED_SET_OPERATION"
    UNSUPPORTED_RELATIONAL_CONSTRUCT = "UNSUPPORTED_RELATIONAL_CONSTRUCT"
    GRAIN_MISMATCH = "GRAIN_MISMATCH"
    DERIVED_RELATION_SCHEMA_MISMATCH = "DERIVED_RELATION_SCHEMA_MISMATCH"
    COMPILATION_FAILED = "COMPILATION_FAILED"
    SEMANTIC_VALIDATION_FAILED = "SEMANTIC_VALIDATION_FAILED"


class SemanticEngineError(ValueError):
    """A deterministic semantic-engine operation failed closed."""

    def __init__(self, code: SemanticFailureCode, message: str) -> None:
        super().__init__(message)
        self.code = code
        self.message = message


class SemanticValidationError(SemanticEngineError):
    pass


class SemanticCompilationError(SemanticEngineError):
    pass
