import { useMemo, useState } from "react";
import type { Decision, RunSummary, RuntimeOutcome } from "../types";
import { StatusBadge } from "../components/StatusBadge";

export function Runs({ runs, onSelect }: { runs: RunSummary[]; onSelect: (run: RunSummary) => void }) {
  const [decision, setDecision] = useState<Decision | "ALL">("ALL");
  const [runtime, setRuntime] = useState<RuntimeOutcome | "ALL">("ALL");
  const filtered = useMemo(() => runs.filter((run) => (decision === "ALL" || run.model_decision === decision) && (runtime === "ALL" || run.runtime_outcome === runtime)), [runs, decision, runtime]);
  return <div className="page-stack"><section className="page-intro"><div><span className="eyebrow accent">HISTORY</span><h2>Recent runs</h2><p>Bounded operator history from this local console instance.</p></div><span className="count-pill">{filtered.length} / {runs.length} runs</span></section><section className="card filters"><label>Model decision<select value={decision} onChange={(event) => setDecision(event.target.value as Decision | "ALL")}><option value="ALL">All decisions</option><option value="ANSWER">ANSWER</option><option value="BLOCKED_AUTHORITY">BLOCKED_AUTHORITY</option><option value="NEEDS_CLARIFICATION">NEEDS_CLARIFICATION</option><option value="BLOCKED_POLICY">BLOCKED_POLICY</option></select></label><label>Runtime<select value={runtime} onChange={(event) => setRuntime(event.target.value as RuntimeOutcome | "ALL")}><option value="ALL">All outcomes</option><option value="EXECUTED">EXECUTED</option><option value="AUTHORITY_REJECTED">AUTHORITY_REJECTED</option><option value="POLICY_REJECTED">POLICY_REJECTED</option><option value="NOT_ENTERED">NOT_ENTERED</option><option value="EXECUTION_ERROR">EXECUTION_ERROR</option></select></label></section><section className="card table-card">{filtered.length ? <table className="runs-table"><thead><tr><th>Run</th><th>Question</th><th>Source</th><th>Model decision</th><th>Runtime</th><th>Latency</th><th>Rows</th></tr></thead><tbody>{filtered.map((run) => <tr tabIndex={0} key={run.run_id} onClick={() => onSelect(run)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onSelect(run); } }}><td><code>{run.run_id}</code><small>{new Date(run.created_at).toLocaleTimeString()}</small></td><td className="question-cell">{run.question}</td><td><span className={`source-badge ${run.proposal_source.toLowerCase()}`}>{run.proposal_source.replaceAll("_", " ")}</span></td><td><StatusBadge value={run.model_decision ?? "NO_DECISION"} /></td><td><StatusBadge value={run.runtime_outcome} /></td><td>{run.duration_ms?.toFixed(0) ?? "—"} ms</td><td>{run.row_count}</td></tr>)}</tbody></table> : <div className="empty-state compact"><div className="empty-icon" aria-hidden="true" /><h3>No matching runs</h3><p>Try another filter or run a new request.</p></div>}</section></div>;
}
